# Generated by Django 4.0.5 on 2022-06-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='website/')),
                ('title', models.CharField(max_length=155)),
                ('content', models.TextField()),
            ],
        ),
    ]
